import type { DailyMeta, DailyRecord } from '../utils/dailyData';

const NS = 'http://www.w3.org/2000/svg';
const DAY_MS = 86400000;
const MONTHS = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
export const YEAR_COLORS = ['#2563eb','#e11d48','#059669','#d97706','#7c3aed','#0891b2','#be123c','#4d7c0f'];
export type MetricKey = 'guitar'|'audiobook'|'running'|'diary'|'dance'|'work'|'language'|'treadmill';
export type ViewKey = 'daily'|'weekly'|'monthly'|'cumulative';
export type RangeKey = 'year'|'ytd'|'30'|'90'|'lifetime'|'custom';
type StateKey = 'before'|'missing'|'zero'|'recorded'|'partial'|'future';
export type Metric = { key:MetricKey; label:string; icon:string; unit:string; digits:number; start:string; value:(record:DailyRecord)=>number|null };
export type Point = { key:string; label:string; date:string|null; value:number|null; state:StateKey; records:DailyRecord[] };
export type Series = { year:number|null; color:string; selected:boolean; dashed:boolean; points:Point[] };

export const METRICS: Record<MetricKey,Metric> = {
  guitar:{key:'guitar',label:'Guitar',icon:'🎸',unit:'hours',digits:1,start:'2023-09-27',value:r=>r.hobbies.guitarMinutes===null?null:r.hobbies.guitarMinutes/60},
  audiobook:{key:'audiobook',label:'Audiobooks',icon:'📚',unit:'hours',digits:1,start:'2023-02-10',value:r=>r.audiobook.minutes===null?null:r.audiobook.minutes/60},
  running:{key:'running',label:'Running',icon:'🏃',unit:'miles',digits:1,start:'2023-09-26',value:r=>r.hobbies.runningMiles},
  diary:{key:'diary',label:'Diary',icon:'📓',unit:'words',digits:0,start:'2022-03-16',value:r=>r.diary.words},
  dance:{key:'dance',label:'Dance',icon:'💃',unit:'hours',digits:1,start:'2026-06-02',value:r=>r.hobbies.danceMinutes===null?null:r.hobbies.danceMinutes/60},
  work:{key:'work',label:'Work',icon:'🧠',unit:'hours',digits:1,start:'2023-05-10',value:r=>r.work.hours},
  language:{key:'language',label:'Language study',icon:'🌍',unit:'hours',digits:1,start:'2023-02-08',value:r=>r.hobbies.languageMinutes===null?null:r.hobbies.languageMinutes/60},
  treadmill:{key:'treadmill',label:'Treadmill',icon:'🚶',unit:'miles',digits:1,start:'2022-12-02',value:r=>r.hobbies.treadmillMiles},
};

const parseIso=(value:string)=>new Date(`${value}T12:00:00`);
export const iso=(date:Date)=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
const addDays=(date:Date,days:number)=>new Date(date.getTime()+days*DAY_MS);
const clampDate=(value:string,min:string,max:string)=>value<min?min:value>max?max:value;
export const sum=(values:Array<number|null>)=>values.reduce((total,value)=>total+(value??0),0);
export const average=(values:Array<number|null>)=>{const valid=values.filter((value):value is number=>value!==null&&Number.isFinite(value));return valid.length?sum(valid)/valid.length:null;};
export const fmt=(value:number|null,digits=0)=>value===null||!Number.isFinite(value)?'—':new Intl.NumberFormat('en-US',{maximumFractionDigits:digits}).format(value);
const compact=(value:number)=>{const abs=Math.abs(value);if(abs>=1000000)return `${fmt(value/1000000,Number.isInteger(value/1000000)?0:1)}m`;if(abs>=1000)return `${fmt(value/1000,Number.isInteger(value/1000)?0:1)}k`;return fmt(value,Number.isInteger(value)?0:1);};
export const prettyDate=(value:string)=>new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric'}).format(parseIso(value));
export const shortDate=(value:string)=>new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric'}).format(parseIso(value));
const svg=(tag:string,attrs:Record<string,string|number>={})=>{const node=document.createElementNS(NS,tag);Object.entries(attrs).forEach(([key,value])=>node.setAttribute(key,String(value)));return node;};
export const waitFor=async(selector:string,attempts=500)=>{for(let i=0;i<attempts;i+=1){const node=document.querySelector(selector);if(node instanceof HTMLElement)return node;await new Promise(resolve=>setTimeout(resolve,25));}return null;};
export const setText=(root:ParentNode,selector:string,value:string)=>{const node=root.querySelector(selector);if(node)node.textContent=value;};

function tooltip(){let node=document.querySelector('.sev2-tooltip') as HTMLElement|null;if(!node){node=document.createElement('div');node.className='sev2-tooltip';node.hidden=true;node.setAttribute('role','tooltip');document.body.append(node);}return node;}
function bindTooltip(target:SVGElement,text:string){const tip=tooltip();target.classList.add('sev2-point');target.setAttribute('tabindex','0');target.setAttribute('aria-label',text);const position=(x:number,y:number)=>{tip.style.left=`${x}px`;tip.style.top=`${y}px`;requestAnimationFrame(()=>{const box=tip.getBoundingClientRect();if(box.right>innerWidth-8)tip.style.left=`${Math.max(8,x-box.width-20)}px`;if(box.top<8)tip.style.top=`${Math.min(innerHeight-8,y+box.height+18)}px`;});};const show=(event:Event)=>{const pointer=event as PointerEvent;tip.textContent=text;tip.hidden=false;position(pointer.clientX,pointer.clientY);};const focus=()=>{const box=target.getBoundingClientRect();tip.textContent=text;tip.hidden=false;position(box.left+box.width/2,box.top);};const hide=()=>{tip.hidden=true;};target.addEventListener('pointerenter',show);target.addEventListener('pointermove',show);target.addEventListener('pointerleave',hide);target.addEventListener('focus',focus);target.addEventListener('blur',hide);}
function niceScale(maximumValue:number){const maximum=Math.max(0,maximumValue);const rough=Math.max(Number.EPSILON,maximum/5);const magnitude=10**Math.floor(Math.log10(rough));const normalized=rough/magnitude;const nice=normalized<=1?1:normalized<=2?2:normalized<=5?5:10;const step=Math.max(Number.EPSILON,nice*magnitude);const max=Math.max(step,Math.ceil(maximum/step)*step);return{maximum:max,step,intervals:Math.max(1,Math.round(max/step))};}

function pointState(date:string,record:DailyRecord|undefined,metric:Metric,dataThrough:string):Point{
  if(date<metric.start)return{key:date,label:shortDate(date),date,value:null,state:'before',records:[]};
  if(date>dataThrough)return{key:date,label:shortDate(date),date,value:null,state:'future',records:[]};
  if(!record)return{key:date,label:shortDate(date),date,value:null,state:'missing',records:[]};
  const value=metric.value(record);
  if(value===null)return{key:date,label:shortDate(date),date,value:null,state:'missing',records:[record]};
  if(record.status==='partial')return{key:date,label:shortDate(date),date,value,state:'partial',records:[record]};
  return{key:date,label:shortDate(date),date,value,state:value===0?'zero':'recorded',records:[record]};
}

function dailyPoints(records:DailyRecord[],metric:Metric,start:string,end:string,dataThrough:string){const map=new Map(records.map(record=>[record.date,record]));const output:Point[]=[];for(let date=parseIso(start);date<=parseIso(end);date=addDays(date,1)){const key=iso(date);output.push(pointState(key,map.get(key),metric,dataThrough));}return output;}
function isoWeek(date:Date){const current=new Date(Date.UTC(date.getFullYear(),date.getMonth(),date.getDate()));const day=current.getUTCDay()||7;current.setUTCDate(current.getUTCDate()+4-day);const yearStart=new Date(Date.UTC(current.getUTCFullYear(),0,1));return Math.ceil((((current.getTime()-yearStart.getTime())/DAY_MS)+1)/7);}
function aggregate(points:Point[],view:'weekly'|'monthly'){const groups=new Map<string,Point[]>();points.forEach(point=>{if(!point.date)return;const date=parseIso(point.date);const key=view==='monthly'?point.date.slice(0,7):`${date.getFullYear()}-W${String(isoWeek(date)).padStart(2,'0')}`;if(!groups.has(key))groups.set(key,[]);groups.get(key)!.push(point);});return Array.from(groups,([key,list])=>{const measured=list.filter(point=>point.value!==null&&['recorded','zero','partial'].includes(point.state));let state:StateKey='missing';if(list.every(point=>point.state==='before'))state='before';else if(list.every(point=>point.state==='future'))state='future';else if(measured.length){state=list.some(point=>point.state==='partial'||point.state==='future')?'partial':sum(measured.map(point=>point.value))===0?'zero':'recorded';}const first=list[0]?.date||null;const date=first?parseIso(first):new Date();const label=view==='monthly'?`${MONTHS[date.getMonth()]} ${date.getFullYear()}`:`Week ${Number(key.slice(-2))}`;return{key,label,date:first,value:measured.length?sum(measured.map(point=>point.value)):null,state,records:list.flatMap(point=>point.records)};}).sort((a,b)=>a.key.localeCompare(b.key));}
function cumulative(points:Point[]){let running=0;return points.map(point=>{if(point.value!==null)running+=point.value;return{...point,value:point.value===null&&running===0?null:running};});}

export function calendarBounds(year:number,range:RangeKey,metric:Metric,meta:DailyMeta,customStart:string,customEnd:string){const first=meta.availableYears.length?`${Math.min(...meta.availableYears)}-01-01`:metric.start;const last=meta.dataThrough||iso(new Date());if(range==='30')return{start:iso(addDays(parseIso(last),-29)),end:last};if(range==='90')return{start:iso(addDays(parseIso(last),-89)),end:last};if(range==='lifetime')return{start:metric.start<first?metric.start:first,end:last};if(range==='custom')return{start:clampDate(customStart||first,first,last),end:clampDate(customEnd||last,first,last)};const start=`${year}-01-01`;if(range==='ytd'){const throughYear=Number(last.slice(0,4));const end=year===throughYear?last:`${year}-${last.slice(5)}`;return{start,end:clampDate(end,start,`${year}-12-31`) };}return{start,end:`${year}-12-31`};}
export function seriesFor(records:DailyRecord[],metric:Metric,view:ViewKey,bounds:{start:string;end:string},meta:DailyMeta){const daily=dailyPoints(records,metric,bounds.start,bounds.end,meta.dataThrough||bounds.end);if(view==='daily')return daily;if(view==='weekly')return aggregate(daily,'weekly');const monthly=aggregate(daily,'monthly');return view==='cumulative'?cumulative(monthly):monthly;}
export function measured(points:Point[]){return points.filter(point=>point.value!==null&&['recorded','zero','partial'].includes(point.state));}

export function rollingBest(points:Point[],window:number){let bestValue:number|null=null;let bestStart:string|null=null;for(let i=0;i<=points.length-window;i+=1){const slice=points.slice(i,i+window);const values=slice.map(point=>point.value);if(!values.some(value=>value!==null))continue;const value=sum(values);if(bestValue===null||value>bestValue){bestValue=value;bestStart=slice[0]?.date||null;}}return{value:bestValue,start:bestStart};}
export function streaks(points:Point[]){let longest=0,current=0,run=0;points.forEach(point=>{if((point.value??0)>0&&['recorded','partial'].includes(point.state)){run+=1;longest=Math.max(longest,run);}else run=0;});for(let i=points.length-1;i>=0;i-=1){const point=points[i];if(point.state==='future')continue;if((point.value??0)>0&&['recorded','partial'].includes(point.state))current+=1;else break;}return{current,longest};}

function stateColor(state:StateKey,value:number|null,maximum:number){if(state==='before')return'#cbd5e1';if(state==='missing')return'#e2e8f0';if(state==='zero')return'#94a3b8';if(state==='partial')return'#f59e0b';if(state==='future')return'#f1f5f9';const ratio=maximum>0?(value??0)/maximum:0;return ratio>.75?'#1d4ed8':ratio>.45?'#3b82f6':ratio>.2?'#60a5fa':'#93c5fd';}
function drawAxes(chart:SVGSVGElement,scale:{maximum:number;step:number;intervals:number},margin:{left:number;right:number;top:number;bottom:number},width:number,height:number){const innerH=height-margin.top-margin.bottom;for(let i=0;i<=scale.intervals;i+=1){const value=scale.maximum-scale.step*i;const y=margin.top+innerH*i/scale.intervals;chart.append(svg('line',{x1:margin.left,x2:width-margin.right,y1:y,y2:y,class:'sev2-grid'}));const text=svg('text',{x:margin.left-10,y:y+4,'text-anchor':'end',class:'sev2-axis'});text.textContent=compact(value);chart.append(text);}}
function drawReference(chart:SVGSVGElement,value:number|null,scale:{maximum:number},margin:{left:number;right:number;top:number;bottom:number},width:number,height:number,label:string){if(value===null||value<0||value>scale.maximum)return;const innerH=height-margin.top-margin.bottom;const y=margin.top+innerH-(value/scale.maximum)*innerH;chart.append(svg('line',{x1:margin.left,x2:width-margin.right,y1:y,y2:y,class:'sev2-reference-line'}));const text=svg('text',{x:width-margin.right-4,y:y-6,'text-anchor':'end',class:'sev2-axis'});text.textContent=label;chart.append(text);}

export function drawTimeline(host:HTMLElement,series:Series[],metric:Metric,view:ViewKey,reference:number|null,referenceLabel:string){const width=1100,height=420,margin={left:76,right:24,top:30,bottom:64};const innerW=width-margin.left-margin.right,innerH=height-margin.top-margin.bottom;const all=series.flatMap(item=>item.points).map(point=>point.value).filter((value):value is number=>value!==null);const scale=niceScale(Math.max(0,...all));const chart=svg('svg',{viewBox:`0 0 ${width} ${height}`,role:'img','aria-label':`${metric.label} ${view} chart`}) as SVGSVGElement;drawAxes(chart,scale,margin,width,height);drawReference(chart,reference,scale,margin,width,height,referenceLabel);
  const maxLength=Math.max(1,...series.map(item=>item.points.length));const slot=innerW/Math.max(1,maxLength-1);const x=(index:number)=>margin.left+slot*index;const y=(value:number)=>margin.top+innerH-(value/scale.maximum)*innerH;const selectedSeries=series.find(item=>item.selected)??series[0];const trackingIndex=selectedSeries?.points.findIndex(point=>Boolean(point.date&&point.date>=metric.start))??-1;if(trackingIndex>=0){const trackX=x(trackingIndex);chart.append(svg('line',{x1:trackX,x2:trackX,y1:margin.top,y2:margin.top+innerH,class:'sev2-tracking-line'}));const trackLabel=svg('text',{x:trackX+5,y:margin.top+13,class:'sev2-axis'});trackLabel.textContent='Tracking begins';chart.append(trackLabel);}
  if(series.length===1&&view==='daily'){const points=series[0].points;const barWidth=Math.max(1,innerW/Math.max(1,points.length)*.72);points.forEach((point,index)=>{const heightValue=point.value===null?3:Math.max(point.value===0?2:3,(point.value/scale.maximum)*innerH);const rect=svg('rect',{x:x(index)-barWidth/2,y:margin.top+innerH-heightValue,width:barWidth,height:heightValue,rx:Math.min(2,barWidth/2),fill:stateColor(point.state,point.value,scale.maximum)});bindTooltip(rect,`${point.label} · ${point.state==='before'?'Before tracking began':point.state==='missing'?'Not logged':point.state==='future'?'Future date':`${fmt(point.value,metric.digits)} ${metric.unit}${point.state==='partial'?' · partial day':''}`}`);if(point.date)rect.addEventListener('click',()=>location.href=`/day/?date=${point.date}`);chart.append(rect);});}
  else{[...series].sort((a,b)=>Number(a.selected)-Number(b.selected)).forEach(item=>{let segment:Array<{x:number;y:number}>=[];const flush=()=>{if(segment.length>1){chart.append(svg('path',{d:segment.map((point,index)=>`${index?'L':'M'} ${point.x} ${point.y}`).join(' '),fill:'none',stroke:item.color,'stroke-width':item.selected?3.4:2,'stroke-linecap':'round','stroke-linejoin':'round',opacity:item.selected?1:.72,...(item.dashed?{'stroke-dasharray':'8 7'}:{})}));}segment=[];};item.points.forEach((point,index)=>{if(point.value===null){flush();return;}segment.push({x:x(index),y:y(point.value)});});flush();item.points.forEach((point,index)=>{if(point.value===null)return;const circle=svg('circle',{cx:x(index),cy:y(point.value),r:item.selected?4:3,fill:item.color,opacity:item.selected?1:.8});bindTooltip(circle,`${point.label}${item.year?` ${item.year}`:''} · ${fmt(point.value,metric.digits)} ${metric.unit}`);chart.append(circle);});});}
  const labels=series[0]?.points||[];const labelStep=view==='daily'?Math.max(1,Math.ceil(labels.length/12)):view==='weekly'?Math.max(1,Math.ceil(labels.length/12)):1;labels.forEach((point,index)=>{if(index%labelStep!==0&&index!==labels.length-1)return;const text=svg('text',{x:x(index),y:height-30,'text-anchor':index===0?'start':index===labels.length-1?'end':'middle',class:'sev2-axis'});text.textContent=view==='daily'&&point.date?MONTHS[parseIso(point.date).getMonth()]:point.label.replace(/ \d{4}$/,'');chart.append(text);});const yTitle=svg('text',{x:-(margin.top+innerH/2),y:18,transform:'rotate(-90)','text-anchor':'middle',class:'sev2-axis-title'});yTitle.textContent=metric.unit;chart.append(yTitle);host.replaceChildren(chart);}

export function drawHeatmap(host:HTMLElement,points:Point[],metric:Metric,year:number){const width=1050,height=250,margin={left:70,right:25,top:30,bottom:45};const cell=Math.min(17,(width-margin.left-margin.right)/54);const chart=svg('svg',{viewBox:`0 0 ${width} ${height}`,role:'img','aria-label':`${metric.label} calendar heatmap for ${year}`});const max=Math.max(0,...points.map(point=>point.value??0));const first=new Date(year,0,1,12);const mondayOffset=(first.getDay()+6)%7;points.forEach((point,index)=>{const position=index+mondayOffset;const week=Math.floor(position/7),day=position%7;const rect=svg('rect',{x:margin.left+week*cell,y:margin.top+day*cell,width:cell-2,height:cell-2,rx:2,fill:stateColor(point.state,point.value,max)});bindTooltip(rect,`${point.label}, ${year} · ${point.state==='before'?'Before tracking began':point.state==='missing'?'Not logged':point.state==='future'?'Future date':`${fmt(point.value,metric.digits)} ${metric.unit}${point.state==='partial'?' · partial day':''}`}`);if(point.date)rect.addEventListener('click',()=>location.href=`/day/?date=${point.date}`);chart.append(rect);});['Mon','Wed','Fri','Sun'].forEach((label,i)=>{const day=[0,2,4,6][i];const text=svg('text',{x:margin.left-8,y:margin.top+day*cell+cell*.65,'text-anchor':'end',class:'sev2-axis'});text.textContent=label;chart.append(text);});for(let month=0;month<12;month+=1){const date=new Date(year,month,1,12);const dayIndex=Math.floor((date.getTime()-first.getTime())/DAY_MS)+mondayOffset;const text=svg('text',{x:margin.left+Math.floor(dayIndex/7)*cell,y:height-20,class:'sev2-axis'});text.textContent=MONTHS[month];chart.append(text);}host.replaceChildren(chart);}

export function lifetimeReference(records:DailyRecord[],metric:Metric,view:ViewKey,meta:DailyMeta){const start=metric.start<`${Math.min(...meta.availableYears)}-01-01`?`${Math.min(...meta.availableYears)}-01-01`:metric.start;const points=seriesFor(records,metric,view,{start,end:meta.dataThrough||iso(new Date())},meta);return average(measured(points).map(point=>point.value));}
